// This file is automatically generated from fonts.h.mako
// DO NOT EDIT
#ifndef __FONTS_H__
#define __FONTS_H__
<%
def C02hex(bs:bytes):
    return "".join(["0x{:02x},".format(x) for x in bs])
%>\

<%size=0%>\
#include <stdint.h>
uint8_t xiangsu12[]={
% for f in fonts:
    ${C02hex(f)} 
<%size+=len(f)%>\
% endfor
};
uint32_t xiangsu12_SIZE = ${size};

#endif