// This file is automatically generated from images.h.mako
// DO NOT EDIT
#ifndef __IMAGES565_H__
#define __IMAGES565_H__
<%
def C02hex(bs:bytes):
    return "".join(["0x{:02x},".format(x) for x in bs])
%>\

#include <stdint.h>
% for name in images:
uint8_t IMG_${name}[] = {${C02hex(images[name])}};
size_t IMG_${name}_SIZE = ${len(images[name])};
size_t IMG_${name}_W = ${sizes[name][0]};
size_t IMG_${name}_H = ${sizes[name][1]};
% endfor

#endif